### ISSUE TITLE
lbac-1-general-project-structure

### ISSUE THREAD

**Issue by slynnda** [slynnda/lbac#1]
### General Project Structure

This task revolves around deciding what kind of structure we want the project to have (initially, as this may and will probably change in the future). Things to do in this task are:
- Set up "stack": Dependency management and build tool for Haskell
- Decide on unit testing tools
- Figure out broad architectural vision for project

**Comment by slynnda** [comment]
Assignees:
@argonauthills
@sophialhudson

**Comment by jasonahills** [comment]
An article about installing Stack:  
http://seanhess.github.io/2015/08/04/practical-haskell-getting-started.html

**Comment by slynnda** [comment]
I'm going to make this recommendation for our initial testing framework:
[QuickCheck](https://wiki.haskell.org/Introduction_to_QuickCheck1)

**Comment by jasonahills** [comment]
Quickcheck Manual:

https://github.com/stackbuilders/quickcheck-manual
